### ISSUE TITLE
The dependency version 1.0.3 doesn't exist

### ISSUE THREAD

**Issue by wmzzh117** [Autodesk-Forge/forge-api-java-client#39]
I added the following dependencies to my pom.xml
``` xml
<dependency>
    <groupId>com.autodesk</groupId>
    <artifactId>forge-java-sdk</artifactId>
     <version>1.0.3</version>
</dependency>
```
When I call `DerivativesApi.getManifest` but throw exception.

``` java
Caused by: com.sun.jersey.api.client.ClientHandlerException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.autodesk.client.model.ManifestChildren$RoleEnum` from String "Autodesk.AEC.ModelData": value not one of declared Enum instance names: [3d, 2d, ifc, graphics, thumbnail, manifest, Autodesk.CloudPlatform.PropertyDatabase]
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 28, column: 19] (through reference chain: com.autodesk.client.model.Manifest["derivatives"]->java.util.ArrayList[0]->com.autodesk.client.model.ManifestDerivative["children"]->java.util.ArrayList[1]->com.autodesk.client.model.ManifestChildren["role"])
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:644) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:604) ~[jersey-client-1.19.1.jar!/:1.19.1]
        at com.autodesk.client.ApiClient.invokeAPI(ApiClient.java:571) ~[forge-java-sdk-1.0.3.jar!/:na]
        at com.autodesk.client.api.DerivativesApi.getManifest(DerivativesApi.java:278) ~[forge-java-sdk-1.0.3.jar!/:na]
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.autodesk.client.model.ManifestChildren$RoleEnum` from String "Autodesk.AEC.ModelData": value not one of declared Enum instance names: [3d, 2d, ifc, graphics, thumbnail, manifest, Autodesk.CloudPlatform.PropertyDatabase]
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 28, column: 19] (through reference chain: com.autodesk.client.model.Manifest["derivatives"]->java.util.ArrayList[0]->com.autodesk.client.model.ManifestDerivative["children"]->java.util.ArrayList[1]->com.autodesk.client.model.ManifestChildren["role"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965) ~[jackson-databind-2.9.9.jar!/:2.9.9]
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815) ~[jackson-jaxrs-base-2.9.9.jar!/:2.9.9]
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634) ~[jersey-client-1.19.1.jar!/:1.19.1]
        ... 22 common frames omitted
```

It seems like https://github.com/Autodesk-Forge/forge-api-java-client/issues/28#issue-495546569. 

and I see it's merged, but I didn't find any maven releases > 1.0.3

that there are only 1.0.2 version https://github.com/Autodesk-Forge/forge-api-java-client/blob/master/pom.xml

**Comment by dukedhx** [comment]
havent released to maven for a while so pull from this repo to use recent fixes
